### ISSUE TITLE
critical regex bugs in getChannelVideosMore()

### ISSUE THREAD

**Issue by gurumnyang** [FreeTubeApp/yt-channel-info#118]
`TypeError: Cannot read properties of null (reading '1')`
`yt-channel-info\app\youtube-grabber.js:266:176`

```
const firstVideoTitle = continuationData[0].richItemRenderer.content.videoRenderer.title
      const firstPublishTimeText = continuationData[0].richItemRenderer.content.videoRenderer.publishedTimeText

      channelInfo = {
        channelId: channelPageResponse.data.responseContext.serviceTrackingParams.find((service) => service.service === 'GOOGLE_HELP').params[0].value,
        channelName: new RegExp(`${firstVideoTitle.runs[0].text} by (.*?) ${firstPublishTimeText.simpleText}`, 'g').exec(firstVideoTitle.accessibility.accessibilityData.label)[1]    //problem
      }
    }
```
It appears to extract the `channelName` from `firstVideoTitle.accessibility.accessibilityData.label` using regex.
The problem is that if `'firstVideoTitle.runs[0].text'` or `'firstPublishTimeText.simpleText'` within RegExp contains regex expressions(or detected to), it can cause extract failure(return null), or incorrect data is determined as channalName.

For example, extract is failed from titles that contain words that can be recognized as regex expression,
 such as `[hello world!] by GurumNyang 1 hour ago`

Special characters should be removed so that some of the titles are not recognized as regex expressions, or if null is returned, improvements should be made to facilitate processing

**Comment by ChunkyProgrammer** [comment]
#116 should fix the issue

**Comment by bonesoul** [comment]
I'm still getting this issue with:

```
TypeError: Cannot read properties of null (reading '1')
    at YoutubeGrabber.getChannelVideosMore (E:\source\vizesizgezi\tasks\node_modules\yt-channel-info\app\youtube-grabber.js:266:176)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ApiReader.queryChannel (file:///E:/source/vizesizgezi/tasks/dist/src/tasks/traveller/api.js:46:23)
```

I have no idea why I'm getting this error.

Yet again a regexp issue.

https://www.youtube.com/watch?v=fjyHMMzZa0s
`9/1 03:29:55 [+101ms] - error: youtube channel query failed for traveller  birhayalinpesinde - Invalid regular expression: /+13 Soruda Karavan Alınır Mı ? Kaça Patlar ? (Karavanda Yaşamanın Artıları VS Eksileri) by (.*?) 1 year ago/: Nothing to repeat`

**Comment by ChunkyProgrammer** [comment]
> I'm still getting this issue with:
> 
> ```
> TypeError: Cannot read properties of null (reading '1')
>     at YoutubeGrabber.getChannelVideosMore (E:\source\vizesizgezi\tasks\node_modules\yt-channel-info\app\youtube-grabber.js:266:176)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async ApiReader.queryChannel (file:///E:/source/vizesizgezi/tasks/dist/src/tasks/traveller/api.js:46:23)
> ```
> 
> I have no idea why I'm getting this error.
> 
> Yet again a regexp issue.
> 
> https://www.youtube.com/watch?v=fjyHMMzZa0s `9/1 03:29:55 [+101ms] - error: youtube channel query failed for traveller birhayalinpesinde - Invalid regular expression: /+13 Soruda Karavan Alınır Mı ? Kaça Patlar ? (Karavanda Yaşamanın Artıları VS Eksileri) by (.*?) 1 year ago/: Nothing to repeat`

Are you using a github version or npm? Npm hasnt been updated so you'd need to use the github version in your package.json  if that's the case

**Comment by bonesoul** [comment]
@ChunkyProgrammer yes I'm using the npm version. Should i use this tag? https://github.com/FreeTubeApp/yt-channel-info/releases/tag/v3.2.1
